export const COLORS = {
  primary: "#236c42",
  primaryDark: "#1a5c38",
  primaryLight: "#e8f5e9",
  white: "#ffffff",
  border: "#e0e0e0",
  text: "#333333",
  textLight: "#666666",
};

export const styles = {
  hero: {
    background: "linear-gradient(135deg, #236c42 0%, #1a5c38 100%)",
    color: COLORS.white,
    padding: "4rem 2rem",
    textAlign: "center",
    fontFamily: "sans-serif",
  },
  heroTitle: {
    fontSize: "2.5rem",
    fontWeight: "700",
    margin: "0 0 1rem",
    lineHeight: "1.2",
  },
  heroSub: {
    fontSize: "1.1rem",
    margin: "0 0 2rem",
    maxWidth: "600px",
    marginLeft: "auto",
    marginRight: "auto",
    opacity: 0.9,
  },
  section: {
    padding: "3rem 2rem",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  sectionTitle: {
    fontSize: "2rem",
    fontWeight: "700",
    color: COLORS.text,
    textAlign: "center",
    margin: "0 0 0.5rem",
  },
  sectionSub: {
    fontSize: "1rem",
    color: COLORS.textLight,
    textAlign: "center",
    margin: "0 0 2rem",
  },
  navBtn: {
    background: COLORS.primary,
    color: COLORS.white,
    border: "none",
    borderRadius: "8px",
    padding: "10px 24px",
    fontSize: "0.95rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background 0.3s",
  },
  btnOutline: {
    background: "transparent",
    color: COLORS.primary,
    border: `2px solid ${COLORS.primary}`,
    borderRadius: "8px",
    padding: "8px 24px",
    fontSize: "0.95rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: "2rem",
    marginTop: "2rem",
  },
};
